### ISSUE TITLE
Remove?

### ISSUE THREAD

**Issue by bjones1** [bnmnetp/BookServer#16]
https://github.com/bnmnetp/BookServer/blob/d3defb16e78d3235a7fcfea632d54685bdc6c9d4/bookserver/main.py#L33

Can this and the commented-out code be removed now?

**Comment by bnmnetp** [comment]
The comment and code can be removed.  It is not an Alembic issue at all.  

the tables are defined in the `startup()` function decorated by `@app.on_event("startup")` in main.py

**Comment by bjones1** [comment]
OK, done -- will update my PR.
