### ISSUE TITLE
Validation strategy

### ISSUE THREAD

**Issue by bjones1** [bnmnetp/BookServer#19]
https://github.com/bnmnetp/BookServer/blob/d3defb16e78d3235a7fcfea632d54685bdc6c9d4/bookserver/crud.py#L84

Should we revalidate here, now that we know what exactly to validate against?

**Comment by bnmnetp** [comment]
How do you propose we revalidate? 

Do we really need to?

The incoming data is validated when the endpoint is activated.  That is passed along to this function.  If the data is not right then the constructor will fail.

**Comment by bnmnetp** [comment]
To be clear, this was definitely just me experimenting and learning about Pydantic. There may well be a better way to take a `schemas.LogItem` and extract only what we need for the answer table object.  Maybe the function should not use the LogItem schema object but rather the autmatically generated answer table schema object?

**Comment by bnmnetp** [comment]
Furthermore I would propose that as a principle we validate things that we don't have control over. Such as incoming data from a web API.  But when it is data from one function to another where we do have control over the data then revalidating is just using up cycles needlessly.   Errors like that should be caught by unit tests.

**Comment by bjones1** [comment]
I agree that all external data be validated, but not internal data. In this case, our external validation doesn't check everything:

1. We haven't included string lengths, so the `LogItemIncoming` schema will pass things the db will reject. (I actually saw an exception from my server recently with exactly this problem.)
2. Some question types (Parsons, perhaps others) require additional fields, but we don't enforce that or check the validity of these fields.

Instead, our `LogItemIncoming` validator should only check that the `event` is valid, then let the table-specific validator check all the other fields.

**Comment by bnmnetp** [comment]
We can add length constraints to our pydantic models.  So I guess we should do that.

Also I think this is a better version of create_answer_table_entry, which could be improved by using a defaultdict for the list of attributes to exclude to handle the parsons problem case.

```python
async def create_answer_table_entry(log_entry: schemas.LogItem):
    log_entry.timestamp = datetime.utcnow()
    tbl = answer_tables[EVENT2TABLE[log_entry.event]]
    new_entry = tbl(
        **log_entry.dict(
            exclude={
                "event",
                "act",
                "timezoneoffset",
                "clientLoginStatus",
                "chapter",
                "subchapter",
                "source",
            }
        )
    )
    async with async_session() as session:
        async with session.begin():
            session.add(new_entry)
    rslogger.debug(f"returning {new_entry}")
    return new_entry
```

**Comment by bnmnetp** [comment]
Actually I think the really elegant solution is to generate schemas for each xxx_answer table and then we can do something like this: `**log_entry.dict(include=set(answer_schema.schema().keys()))`

**Comment by bjones1** [comment]
I'm working on this...it's interesting...

**Comment by bjones1** [comment]
I pushed some WIP on my latest PR that does this (mostly).

**Comment by bnmnetp** [comment]
Are you going to continue to work on crud.py 

- [ ] Add Pydantic return types to crud functions
- [ ] Convert results to Pydantic objects before return

I thought that is what you indicated so I'm going to assign this to you... If I misunderstood let me know.

**Comment by bjones1** [comment]
Yes, I'm mostly done. However, annotating with dynamically-defined types (any of the schemas derived from an SQL model) is mostly useless. The type checker is a static tool and, by definition, can't understand types created by run-time code.

**Comment by bjones1** [comment]
The `reveal_type` function is very helpful to see what mypy sees.

**Comment by bjones1** [comment]
Closing this, we can discuss in the PR.
