### ISSUE TITLE
Port new selenium tests over to BookServer

### ISSUE THREAD

**Issue by bnmnetp** [bnmnetp/BookServer#30]
This would be a big hit for coverage as well as testing ajax.py

@bjones1 do you have any interest in getting these moved over?

**Comment by bjones1** [comment]
Sure, I'll be happy to.

**Comment by bjones1** [comment]
A quick look: the current release of runestone components depends on SQLAlchemy 1.3, while we need 1.4. So, we need a release of Runestone Components with updated dependencies to make much progress. Can you work on this?

**Comment by bjones1** [comment]
Another challenge: there's no way to create a user in the bookserver. I assume I'll need to get the SQL to do it from then execute that.

**Comment by bnmnetp** [comment]
Yes, I just have a .csv file with my own username in it that I load.  But I think we will want a way to initialize the usual courses as well as making some users.

**Comment by bnmnetp** [comment]
Do you need a released runestone or if I have requirements-dev.txt updated on github will that work?

**Comment by bjones1** [comment]
Github should be fine, per https://github.com/python-poetry/poetry/issues/47.

**Comment by bnmnetp** [comment]
I just released 5.6.1 so we should be good either way.

**Comment by bjones1** [comment]
OK, thanks! I'll try it out as soon as it shows up; poetry doesn't see it yet.

**Comment by bnmnetp** [comment]
OK, I can see it on the pypi webpage, but sometimes it takes a bit before the CL utils can see it.

**Comment by bjones1** [comment]
AFAIK, this is done!
