### ISSUE TITLE
JS Dependency problems

### ISSUE THREAD

**Issue by bnmnetp** [bnmnetp/BookServer#59]
@bjones1 

We have a nasty problem in the latest version of `_sphinx_static_files.html`. 

On the one hand jquery needs to be imported before the loop over the files in `webpack_static_imports.json`. But, when we do the menus in the instructor interface to not work!  On the other hand if we import jquery AFTER `webpack_static_imports.json` then all kinds of stuff including selectquestion fails badly.

We need a solution where it all works!  Any ideas?  Does the user menu work for you on your servers?? when you are using the instructor interface??

**Comment by bjones1** [comment]
I'm confused -- this is a bug submitted in the bookserver, but `_sphinx_static_files.html` only exists in the old runestone server AFAIK. The old server is the only thing that has an instructor interface. ???

**Comment by bjones1** [comment]
I also see a commit in the runestone server titled "fix menus for instructor"? Does it work?

**Comment by bjones1** [comment]
I'm running the runestone server from master, just before this commit, and everything seems to work for me.
