### ISSUE TITLE
Port from `databases` to `sqlalchemy` async

### ISSUE THREAD

**Issue by bjones1** [bnmnetp/BookServer#9]
Per https://github.com/bnmnetp/BookServer/pull/8/files#r619874882, remove the use of `databases` in favor of direct use of sqlalchemy async instead.

**Comment by bnmnetp** [comment]
This article gives a pretty good roadmap for using sqlalchemy directly.
I'll make a branch and give it a try today.

**Comment by bjones1** [comment]
Wow, great find! That looks very helpful.

**Comment by bnmnetp** [comment]
Good progress on this today.  I'm nearly back to where I was last Friday.

I'm changing all the models to ORM style for compatibility with the autogenerating pydantic models (mostly copy/pasting from your work)

And learning some new syntax and gotchas.

But... the good news is that it works (even with sqllite)

**Comment by bjones1** [comment]
Wow, very exciting! Thank you! I need to read up more on FastAPI and sqlalchemy, then I'll provide some thoughts.
